[client]
port = 2149
protocol = TCP
user = root
[mysqld]
general_log = 1
report_port = 2149
loose_mysqlx_port = 21490
secure_file_priv = /export/home/jenkins-data/mysql-shell/shell-trace-maker-sandbox/workspace/traceroot/worker14/tmp/2149/mysql-files
pid_file = /export/home/jenkins-data/mysql-shell/shell-trace-maker-sandbox/workspace/traceroot/worker14/tmp/2149/2149.pid
log_error = /export/home/jenkins-data/mysql-shell/shell-trace-maker-sandbox/workspace/traceroot/worker14/tmp/2149/sandboxdata/error.log
datadir = /export/home/jenkins-data/mysql-shell/shell-trace-maker-sandbox/workspace/traceroot/worker14/tmp/2149/sandboxdata
server_id = 14494
port = 2149
transaction_write_set_extraction = XXHASH64
binlog_checksum = NONE
gtid_mode = ON
<<<<<<< HEAD:unittest/traces/5.7.22/Shell_js_dba_tests/dba_configure_new_instance/sandbox_2149_2_my.cnf
auto_increment_offset = 1
=======
auto_increment_offset = 7
>>>>>>> Bug#27986413 RECOVERING GR CLUSTER FROM COMPLETE OUTAGE FAILS WHEN SSL IS DISABLED:unittest/traces/5.7.22/Admin_api_scripted/Auto_script_js/run_and_check/cluster_removeinstance_interactive.js/sandbox_2149_2_my.cnf
basedir = /var/lib/jenkins/shell-deps/traces-mysql-5.7.22-mysql-commercial_5.7.22-1ubuntu16.04_amd64/usr
log_bin
loose_mysqlx_socket = mysqlx.sock
log_slave_updates = ON
relay_log_info_repository = TABLE
innodb_log_file_size = 1M
master_info_repository = TABLE
binlog_format = ROW
innodb_log_buffer_size = 1M
plugin_load = mysqlx.so
enforce_gtid_consistency = ON
innodb_data_file_path = ibdata1:10M:autoextend
socket = mysqld.sock
log_syslog = OFF
